### ISSUE TITLE
有一个问题想请教一下

### ISSUE THREAD

**Issue by fjqisba** [KangLin/RabbitRemoteControl#14]
请问RDP协议支持远程执行命令行吗，我有一个需求，需要能够批量下发cmd命令到服务器中。

**Comment by KangLin** [comment]
没看明白你的需求。请详细描述。最好举例子。

**Comment by KangLin** [comment]
RDP不支持远程执行命令。但支持文件传输。

**Comment by fjqisba** [comment]
感谢解答

**Comment by KangLin** [comment]
RDP协议的 [Remote Programs](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdperp/83275957-2d0e-4c52-88d1-1b4c998c6bec?redirectedfrom=MSDN) 也许可以解决你的需求.
