### ISSUE TITLE
App  auto close (crush)

### ISSUE THREAD

**Issue by PopeyeloveWeed** [KangLin/RabbitRemoteControl#17]
The app autoclose the window when im tryed open it

I tryed two version, but have the same problem 

File log:

156 D:\a\RabbitRemoteControl\RabbitRemoteControl\.cache\source\RabbitCommon\Src\RabbitCommonTools.cpp(117) [0x009a4550] ERROR RabbitCommon - translator install translator fail: C:/Program Files (x86)/Rabbit/RabbitRemoteControl/bin\..\translations/RabbitCommon_en_US.qm
156 D:\a\RabbitRemoteControl\RabbitRemoteControl\App\Viewer\main.cpp(65) [0x009a4550]  INFO Main - Language: en_US
261 (0) [0x009a4550]  WARN Qt default - libpng warning: iCCP: CRC error
273 D:\a\RabbitRemoteControl\RabbitRemoteControl\.cache\source\RabbitCommon\Src\FrmUpdater\FrmUpdater.cpp(108) [0x009a4550] ERROR FrmUpdater - Support ssl: 1; BuildVersion: OpenSSL 1.1.1k  25 Mar 2021 Version: OpenSSL 1.1.1m  14 Dec 2021
273 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::DownloadFile: QUrl("https://raw.githubusercontent.com/KangLin/RabbitRemoteControl/master/Update/update.xml") false false
275 D:\a\RabbitRemoteControl\RabbitRemoteControl\App\Viewer\main.cpp(75) [0x009a4550] ERROR main - GenerateUpdateXml fail
279 (0) [0x009a4550] DEBUG Qt default - GetDirApplication: "C:/Program Files (x86)/Rabbit/RabbitRemoteControl/bin"
281 (0) [0x009a4550] DEBUG Qt default - GetDirApplication: "C:/Program Files (x86)/Rabbit/RabbitRemoteControl/bin"
282 (0) [0x009a4550] DEBUG Qt default - LoadStyle: "C:/Program Files (x86)/Rabbit/RabbitRemoteControl/bin\\..\\data\\style\\black_green.qss"
316 D:\a\RabbitRemoteControl\RabbitRemoteControl\.cache\source\RabbitCommon\Src\FrmUpdater\FrmUpdater.cpp(108) [0x009a4550] ERROR FrmUpdater - Support ssl: 1; BuildVersion: OpenSSL 1.1.1k  25 Mar 2021 Version: OpenSSL 1.1.1m  14 Dec 2021
316 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::DownloadFile: QUrl("https://raw.githubusercontent.com/KangLin/RabbitRemoteControl/master/Update/update.xml") false false
559 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::slotCheck()
565 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::slotDownloadXmlFile
565 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::DownloadFile: QUrl("https://raw.githubusercontent.com/KangLin/RabbitRemoteControl/master/Update/update.xml") false false
565 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater download file:  "C:/Users/USER/AppData/Local/Temp/Rabbit/RabbitRemoteControl/update.xml"
888 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::slotFinished()
890 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::slotCheckXmlFile()
890 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::CheckRedirectXmlFile()
891 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::slotDownloadXmlFile
891 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater::DownloadFile: QUrl("https://github.com/KangLin/RabbitRemoteControl/releases/download/v0.0.18/update_windows.xml") false false
891 (0) [0x009a4550] DEBUG Qt default - CFrmUpdater download file:  "C:/Users/USER/AppData/Local/Temp/Rabbit/RabbitRemoteControl/update_windows.xml"

**Comment by KangLin** [comment]
You are try to delete ~/Documents/Rabbit/RabbitRemoteControl

**Comment by KangLin** [comment]
You try to the new pragram of download from :
https://github.com/KangLin/RabbitRemoteControl/actions/runs/2674824108

Please provide feedback on test results.

**Comment by KangLin** [comment]
FIX the error in https://github.com/KangLin/RabbitCommon/commit/7ed300a206d8a36c30003b6c19ad181682d0ff5f
Please try it download from https://github.com/KangLin/RabbitRemoteControl/actions/runs/2694203344
Please provide feedback on test results. If fail, send core dump file to me.
