### ISSUE TITLE
ERRCONNECT_DNS_NAME_NOT_FOUND

### ISSUE THREAD

**Issue by zgml** [KangLin/RabbitRemoteControl#19]
**Describe the bug**
使用源码编译安装，连接rdp时报错ERRCONNECT_DNS_NAME_NOT_FOUND

**To Reproduce**
1. 编译freerdp 2.10.0
2. 编译RabbitRemoteControl 0.0.26
3. 创建rdp连接，报错DNS_NAME_NOT_FOUND
4. 点击帮助-关于，关闭弹窗
5. rdp连接正常

**Expected behavior**
打开软件，连接rdp，客服端迅速返回The host name is not found，挂起客户端等待数分钟后，连接正常(经过多次测试，并非是挂起，而是点击帮助-关于，然后关闭，随后连接功能正常)
**Screenshots**
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/df0fe5d6-6578-4e8c-a2fa-a55df20179e1)
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/a4d723e9-1e0c-4231-8bba-cdb5694688ce)

**IDA windbg debuger log**
[10:43:34.521 34060|14400 D] FreeRDP.Log - Enabling security layer negotiation: TRUE
[10:43:34.522 34060|14400 D] FreeRDP.Log - Enabling restricted admin mode: FALSE
[10:43:34.522 34060|14400 D] FreeRDP.Log - Enabling RDP security: TRUE
[10:43:34.522 34060|14400 D] FreeRDP.Log - Enabling TLS security: TRUE
[10:43:34.522 34060|14400 D] FreeRDP.Log - Enabling NLA security: TRUE
[10:43:34.523 34060|14400 D] FreeRDP.Log - Enabling NLA extended security: FALSE
[10:43:34.523 34060|14400 D] FreeRDP.Log - rdp_client_transition_to_state CONNECTION_STATE_INITIAL --> CONNECTION_STATE_NEGO
[10:43:34.523 34060|14400 D] FreeRDP.Log - state: NEGO_STATE_NLA
[10:43:34.523 34060|14400 D] FreeRDP.Log - Attempting NLA security
[10:43:34.524 34060|14400 E] FreeRDP.Log - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]
[10:43:34.524 34060|14400 D] FreeRDP.Log - rdp_client_transition_to_state CONNECTION_STATE_NEGO --> CONNECTION_STATE_INITIAL

**Application details**

玉兔远程控制
版本：v0.0.26(校订版本： 86bbcd94) 架构：x86_64
编译日期/时间：Mar 6 2024/10:18:35
文件路径：D:/Projects/VSProjects/RabbitRemoteControl/build/install/bin/RabbitRemoteControlApp.exe
参数：D:\Projects\VSProjects\RabbitRemoteControl\build\install\bin\RabbitRemoteControlApp.exe
插件
自由远程桌面
RDP（ Windows 远程桌面协议）：访问 Windows 远程桌面

FreeRDP 版本：2.10.0
编译版本：2.10.0:2.10.0
编译日期：Mar 6 2024 09:15:42
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_HEADER= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_FAAC=OFF WITH_FAAD2=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_PROXY=OFF WITH_PROXY_MODULES=OFF WITH_SAMPLE=OFF WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VERBOSE_WINPR_ASSERT=ON WITH_WIN8=OFF WITH_WINMM=ON WITH_WINPR_TOOLS=ON Build type: Release CFLAGS: /DWIN32 /D_WINDOWS /Gd /W3 -DWINPR_DLL Compiler: MSVC, 19.29.30151.0 Target architecture: x64

Qt
Qt 运行版本：5.15.2

Qt 编译版本：5.15.2

Qt 库版本：5.15.2

语言：zh_CN

OpenSSL:

编译时版本： OpenSSL 1.1.1g 21 Apr 2020
安装的版本： OpenSSL 1.1.1t 7 Feb 2023

玉兔公共库
版本：v2.0.1-5-gaa7b64d(校订版本： aa7b64d)

**System information**
win10 22H2

**Comment by KangLin** [comment]
解析域名出错，会引起此错误。
此现象是偶然出现，还是必然？
偶然现象的话，应该算是正常。
如果是必然的。我能否运程调试一下？

**Comment by zgml** [comment]
是必然的，我使用IDA调试软件时，点击关于以后，似乎软件加载了一些网络相关的模块。我尝试调试点击关于后的代码，
然后发现一个有趣的事情，当我注释掉Qurl里面三个下载的链接以后，即使点击关于也依然会报错了。这一段的代码似乎调用了系统底层的api接口。感觉似乎是一些本来应该主动加载的模块没有加载，然后通过下载功能又被动加载上了？我的微信cvcccx
result = freerdp_tcp_resolve_host(hostname, port, 0);
if (!result)
{
        freerdp_set_last_error_if_not(context,
FREERDP_ERROR_DNS_NAME_NOT_FOUND);

        return -1;
}
struct addrinfo* freerdp_tcp_resolve_host(const char* hostname, int port,
int ai_flags)
{
        char* service = NULL;
        char port_str[16];
        int status;
        struct addrinfo hints = { 0 };
        struct addrinfo* result = NULL;
        hints.ai_family = AF_UNSPEC;
        hints.ai_socktype = SOCK_STREAM;
        hints.ai_flags = ai_flags;

        if (port >= 0)
        {
                sprintf_s(port_str, sizeof(port_str) - 1, "%d", port);
                service = port_str;
        }

        status = getaddrinfo(hostname, service, &hints, &result);

        if (status)
                return NULL;

        return result;
}



WINAPI
WspiapiGetAddrInfo(
    _In_opt_ const char                       *nodename,
    _In_opt_ const char                       *servname,
    _In_opt_ const struct addrinfo            *hints,
    _Outptr_ struct addrinfo                 **res)
{
    int                             iError;
    static WSPIAPI_PGETADDRINFO     pfGetAddrInfo   = NULL;

    if (!pfGetAddrInfo)
        pfGetAddrInfo   = (WSPIAPI_PGETADDRINFO) WspiapiLoad(0);

    iError = (*pfGetAddrInfo)(nodename, servname, hints, res);
    WSASetLastError(iError);
    return iError;
}

Kang Lin ***@***.***> 于2024年3月6日周三 16:39写道：

**Comment by KangLin** [comment]
我认为可能是你的网络有问题。
明天9:00联系你远程调试一下。






--
发自我的网易邮箱手机智能版



在 2024-03-06 17:14:38，zgml ***@***.***> 写道：


是必然的，我使用IDA调试软件时，点击关于以后，似乎软件加载了一些网络相关的模块。我尝试调试点击关于后的代码，
然后发现一个有趣的事情，当我注释掉Qurl里面三个下载的链接以后，即使点击关于也依然会报错了。这一段的代码似乎调用了系统底层的api接口。感觉似乎是一些本来应该主动加载的模块没有加载，然后通过下载功能又被动加载上了？我的微信cvcccx
result = freerdp_tcp_resolve_host(hostname, port, 0);
if (!result)
{
freerdp_set_last_error_if_not(context,
FREERDP_ERROR_DNS_NAME_NOT_FOUND);

return -1;
}
struct addrinfo* freerdp_tcp_resolve_host(const char* hostname, int port,
int ai_flags)
{
char* service = NULL;
char port_str[16];
int status;
struct addrinfo hints = { 0 };
struct addrinfo* result = NULL;
hints.ai_family = AF_UNSPEC;
hints.ai_socktype = SOCK_STREAM;
hints.ai_flags = ai_flags;

if (port >= 0)
{
sprintf_s(port_str, sizeof(port_str) - 1, "%d", port);
service = port_str;
}

status = getaddrinfo(hostname, service, &hints, &result);

if (status)
return NULL;

return result;
}



WINAPI
WspiapiGetAddrInfo(
_In_opt_ const char *nodename,
_In_opt_ const char *servname,
_In_opt_ const struct addrinfo *hints,
_Outptr_ struct addrinfo **res)
{
int iError;
static WSPIAPI_PGETADDRINFO pfGetAddrInfo = NULL;

if (!pfGetAddrInfo)
pfGetAddrInfo = (WSPIAPI_PGETADDRINFO) WspiapiLoad(0);

iError = (*pfGetAddrInfo)(nodename, servname, hints, res);
WSASetLastError(iError);
return iError;
}

Kang Lin ***@***.***> 于2024年3月6日周三 16:39写道：

**Comment by KangLin** [comment]
检查了代码，在WINDOWS 下 freerdp 插件没有初始化SOCKET。

**Comment by KangLin** [comment]
```
 if(pUpdate->GenerateUpdateXml())
        qCritical(App) << "GenerateUpdateXml fail";
    else
        return 0;
```

这个错误返回已经修改了，你更新最的代码即可。

**Comment by zgml** [comment]
好的，感谢

**Comment by zgml** [comment]
我在构建时关闭了BUILD_UPDATE，可能是这一行为导致了网络初始化失败

**Comment by KangLin** [comment]
> 我在构建时关闭了BUILD_UPDATE，可能是这一行为导致了网络初始化失败


windows 下 SOCKET 初始化在程序中只要初始化一次。
