### ISSUE TITLE
RDP界面存在波纹状的印记

### ISSUE THREAD

**Issue by zgml** [KangLin/RabbitRemoteControl#21]
我使用最新开发分支上的代码编译客户端，freerdp的版本为2.10.0 ，连接远端虚拟机后，界面存在放射状波纹状的印记，如下图所示
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/eb36dc85-9335-4170-8a1d-dc5befdcee3e)
后续我更新连接参数中的颜色深度为32比特，效果稍有提升，但是问题依然存在，如下图
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/4c463986-4a42-4518-8ee3-9abc8d438d6f)
我测试使用2.10.0版本的wfreerdp连接远端，画面效果与玉兔客户端类似，也存在水印问题，如下图
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/d07dd8fe-b22c-4898-8968-2a04f3604fd4)
并且wfreerdp偶尔会出现下图的状况，黑色方块的显示状态和水印相同也是呈放射状
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/71cb1944-c1cb-4f9d-8598-b742eb18fcd0)
后续我编译安装了freerdp的3.4.0版本，使用wfreerdp连接，没有出现水印效果，如下图所示
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/e2d17a76-73d5-419c-9305-70c2288c13b4)
但是将其编译到客户端中，水印问题没有改善，如下图
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/5f646349-6c3a-4ac5-bc90-08d75d31c785)

**Comment by KangLin** [comment]
我没有看出区别 :(

**Comment by zgml** [comment]
![image](https://github.com/KangLin/RabbitRemoteControl/assets/52619631/2cf5620d-42f2-4eb8-91a6-b5636f3cc31b)

**Comment by KangLin** [comment]
可能是缩放的问题：
选择“桌面还原到原始大小”看是否还有些情况
如果还存在问题，则是编码的问题。但这不是BUG。这个是为了适应资源不够的情况。你选择合适的桌面大小与编码与颜色深度，就可以解决。

**Comment by zgml** [comment]
我尝试了 桌面还原到原始大小 波纹的情况依然存在，您说的编码应该在哪里设置

**Comment by KangLin** [comment]
![图片](https://github.com/KangLin/RabbitRemoteControl/assets/8564669/4472e86a-b8f9-447d-822b-8d083d16f1fa)

**Comment by KangLin** [comment]
我试了下，远程颜色深度选24比特，就没有了

**Comment by zgml** [comment]
感谢您的答复，我构建了两个版本的客户端，使用freerdp2.10.0构建的客户端，色深为24比特时波纹确实消失了，但是使用freerdp3.4.0版本构建的客户端选择24比特色深波纹没有改善，并且关闭连接以后，编辑连接属性，色深又会被重置为32位
