### ISSUE TITLE
希望增强断开远程桌面的时候，不关闭远程UI的功能

### ISSUE THREAD

**Issue by skyformat99** [KangLin/RabbitRemoteControl#22]
自动化测试的时候，会使用各种python脚本操作鼠标，键盘等等，进行测试工作；
一般会通过rdp登录远程服务器，在服务器上运行 python脚本测试。

这个时候，如果直接断开 1remote，则远端的python脚本不会正确执行了。

原因就是：
https://learn.microsoft.com/zh-cn/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest

如果使用远程桌面访问以自动登录方式运行代理的计算机，则直接断开连接远程桌面会导致计算机锁定，并且在此代理上运行的任何 UI 测试都可能会失败。 为避免故障，请在远程计算机上使用 [tscon](https://learn.microsoft.com/zh-cn/windows-server/administration/windows-commands/tscon) 命令从远程桌面断开连接。

或者，若要自动查找当前会话 ID，请创建一个包含以下代码的批处理文件：

batch

复制
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
%windir%\System32\tscon.exe %%s /dest:console
)

也可以参考这个方法：
https://blog.csdn.net/qq_51038274/article/details/122223669

总之，希望作者可以集成这个功能，断开的时候，仍然让服务器可以正常执行UI相关的python脚本等功能。

**Comment by KangLin** [comment]
@skyformat99 请提供一个简单的自动化测试和环境，帮助我理解此问题。

**Comment by KangLin** [comment]
@skyformat99 请提供一个简单的自动化测试和环境，帮助我理解此问题。

**Comment by skyformat99** [comment]
> @skyformat99 请提供一个简单的自动化测试和环境，帮助我理解此问题。
> 
> 我的理解是需要你从服务器上用tscon按其介绍的方式断开，而不是从客户端断开。你可以写个脚本就可以完成，没必要由远程控制程序做这个。

对。就是这个意思；关键是有点麻烦。

能不能远控软件上自动释放并运行，断开连接的时候。

**Comment by KangLin** [comment]
这个不属于远程控制软件的功能。

建议你写个退出服务（例如：exit.sever)，然后在服务器上启动。在客户端完成测试程序后，向exit.server发送退出命令即可。客户端监控远程控制软件的进程终止后再退出。
