### ISSUE TITLE
A true multi-screen

### ISSUE THREAD

**Issue by zgml** [KangLin/RabbitRemoteControl#23]
When I use xfreerdp on debian, the multi-screen parameter is enabled, and the display effect of the screen is similar to the mstsc effect on windows, while the multi-screen of this project now seems to be just lengthening the width，When the window is enlarged, the display is not very well

**Comment by KangLin** [comment]
I don't have a multi-screen device, so I didn't complete this part of the function.
Can you contribute?

**Comment by zgml** [comment]
> I don't have a multi-screen device, so I didn't complete this part of the function. Can you contribute?

Ok, I am analyzing the code of freerdp3.6.3 and it seems to introduce a screen layout feature to achieve this function, do you have relevant development ideas and suggestions?

**Comment by zgml** [comment]
![17276660028490](https://github.com/user-attachments/assets/02ac7815-eb1f-471d-b6ca-d390b84b7116)
I finish this part of the code, it seems to work, I move the viewer out of the parent control, the picture is always blurred, it seems that the white border is always affecting the resolution

**Comment by KangLin** [comment]
Please create pull requset

**Comment by zgml** [comment]
> Please create pull requests
The screen parameters are manually set by me, faced with multiple devices and shaped screens, it hardly works, wait for me to improve it
