### ISSUE TITLE
Error starting the program

### ISSUE THREAD

**Issue by volkansari** [KangLin/RabbitRemoteControl#24]
I get this error when I try to start the program. I am using Windows 10 Pro

![Adsız](https://github.com/user-attachments/assets/5a5f8304-d167-47b5-a01d-6e0169d7ba2f)

**Comment by KangLin** [comment]
You are use version? and OS detail?

**Comment by KangLin** [comment]
This is core dump. can send core dump file? the core dump file in the program root folder.

**Comment by volkansari** [comment]
[Uploading RabbitRemoteControl_20241008161545_8660_2460.dmp…]()

**Comment by volkansari** [comment]
[Dump file ---RabbitRemoteControl_20241008161545_8660_2460.dmp](https://github.com/user-attachments/files/17293966/RabbitRemoteControl_20241008161545_8660_2460.dmp)

**Comment by KangLin** [comment]
You look like you're using a very old version from dump file. You are used RabbitRemoteControl version?

- RabbitRemoteControl version:
Menu->Help->Information
- Detail information:
Menu->Help->Information->Detail

Please try to use latest version.

**Comment by KangLin** [comment]
You use v0.0.26, please try to v0.0.27.

**Comment by volkansari** [comment]
I updated from v0.0.26 to v0.0.27 but I still get the same error. Please attach the dump file tomorrow.

**Comment by KangLin** [comment]
Please update v0.0.27 dump file.

**Comment by volkansari** [comment]
[RabbitRemoteControl_20241010130725_4332_2788.dmp…]()

**Comment by volkansari** [comment]
I think it's related to the windows version

**Comment by volkansari** [comment]
windows 10 pro 
version: 1607

**Comment by KangLin** [comment]
> RabbitRemoteControl_20241010130725_4332_2788.dmp…

Link error. please upload again.

**Comment by volkansari** [comment]
[RabbitRemoteControl_20241010130725_4332_2788.dmp](https://github.com/user-attachments/files/17394121/RabbitRemoteControl_20241010130725_4332_2788.dmp)

**Comment by KangLin** [comment]
Please try v0.0.28.
If you still core, send the log file and core dump file .
The log file in %Temp%\log\Rabbit\RabbitRemoteControl
