### ISSUE TITLE
Wake on Lan (WOL)

### ISSUE THREAD

**Issue by volkansari** [KangLin/RabbitRemoteControl#25]
I have been user of Rabbit Remote Control and find its features very valuable. To further enhance its utility, I would like to suggest the addition of Wake-on-LAN (WoL) support. This feature would enable users to remotely wake up devices that are powered off or in sleep mode, making the tool even more versatile.

**Comment by KangLin** [comment]
WOL is supported by the operating system.

I guess you want to wake up the computer with this program?

Please describe your thoughts in detail.

**Comment by volkansari** [comment]
for example 

```
#include <QtNetwork/QUdpSocket>
#include <QHostAddress>
#include <QByteArray>
#include <QNetworkDatagram>
#include <QDebug>

void sendWakeOnLanPacket(const QString &macAddress)
{
    // Parse the MAC address
    QStringList macBytes = macAddress.split(":");
    if (macBytes.size() != 6) {
        qDebug() << "Invalid MAC address";
        return;
    }

    QByteArray macByteArray;
    foreach (const QString &byte, macBytes) {
        bool ok;
        macByteArray.append(byte.toUInt(&ok, 16));
        if (!ok) {
            qDebug() << "Invalid byte in MAC address";
            return;
        }
    }

    // Create the magic packet
    QByteArray magicPacket;
    magicPacket.fill(0xFF, 6);  // Start with 6 bytes of 0xFF
    for (int i = 0; i < 16; ++i) {
        magicPacket.append(macByteArray);  // Repeat MAC address 16 times
    }

    // Send the packet via UDP
    QUdpSocket udpSocket;
    QHostAddress broadcastAddress("255.255.255.255");  // Broadcast address
    udpSocket.writeDatagram(magicPacket, broadcastAddress, 9);  // Use port 9

    if (udpSocket.waitForBytesWritten(3000)) {
        qDebug() << "Magic packet sent successfully!";
    } else {
        qDebug() << "Failed to send magic packet!";
    }
}
```
```
```

**Comment by KangLin** [comment]
There are two or more implementation methods to see which one is suitable.
- To integrate connect dialog

![WakeOnLan](https://github.com/user-attachments/assets/d5c80dca-9630-4d13-bddd-6b9b8c9d0588)

- Make a separate WOL plug-in to manage all the devices that need wake on lan

**Comment by KangLin** [comment]
In the end, I chose the plugin.
![2024_11_22_14_55_38_791](https://github.com/user-attachments/assets/3b096246-8eaa-49ed-a960-e521ed9da4df)

**Comment by KangLin** [comment]
![图片](https://github.com/user-attachments/assets/227efa28-0594-424a-9d77-cb1ede8debe4)
