### ISSUE TITLE
Can a project be developed based on the approximate requirements of this document?

### ISSUE THREAD

**Issue by axt178178** [KangLin/RabbitRemoteControl#26]
[Introduction to Functions - Must Read(译文).pdf](https://github.com/user-attachments/files/17130218/Introduction.to.Functions.-.Must.Read.pdf)

**Comment by KangLin** [comment]
I could consider the following joining features:
- Remote wake-up
- Control record
- Camera preview and recording

**Comment by axt178178** [comment]
Do you have a telegram, we can communicate more deeply and confirm

Kang Lin ***@***.***> 于2024年9月26日周四 09:02写道：

**Comment by KangLin** [comment]
no telegram

**Comment by axt178178** [comment]
So where can I contact you?

Kang Lin ***@***.***> 于2024年9月27日周五 08:30写道：

**Comment by KangLin** [comment]
here. or email





--
发自我的网易邮箱手机智能版



在 2024-09-27 16:31:14，axt178178 ***@***.***> 写道：


So where can I contact you?

Kang Lin ***@***.***> 于2024年9月27日周五 08:30写道：

**Comment by axt178178** [comment]
What's your email address?

Kang Lin ***@***.***> 于2024年9月28日周六 07:19写道：

**Comment by KangLin** [comment]
> I could consider the following joining features:
> 
>     * Remote wake-up
> 
>     * Control record
> 
>     * Camera preview and recording

Try v0.0.28
