### ISSUE TITLE
Ripple on remote screen

### ISSUE THREAD

**Issue by chengzhidada** [KangLin/RabbitRemoteControl#27]
Here is what happened. When I use RDP to connect to windows, when I refresh the page, or zoom in and out of the page, a long rectangle appears from top to bottom of the screen, as if it were a block.

![screenshot-1](https://github.com/user-attachments/assets/789d2439-047e-4449-9059-94396c08543b)
![screenshot-2](https://github.com/user-attachments/assets/2b3f3633-788a-4c40-ae1a-ac0ccd4d7877)

I hope that you can contribute to fixing this problem, and of course, I'll try to fix it too!

**Comment by KangLin** [comment]
> when I refresh the page, or zoom in and out of the page, 

How does operate it?

Can I upload a video?

**Comment by chengzhidada** [comment]
Open an RDP connection, open any window in the remote screen, resize it to minimize it, and then watch the video in full screen, or just watch the video, and try it several times.I'll upload the video later.

**Comment by chengzhidada** [comment]
> > when I refresh the page, or zoom in and out of the page,
> 
> How does operate it?
> 
> Can I upload a video?

Open an RDP connection, open any window in the remote screen, resize it to minimize it, and then watch the video in full screen, or just watch the video, and try it several times.I'll upload the video later.

**Comment by KangLin** [comment]
You turn off the window animation effect in remote desktop. See if it's okay.

**Comment by chengzhidada** [comment]
> > when I refresh the page, or zoom in and out of the page,
> 
> How does operate it?
> 
> Can I upload a video?


https://github.com/user-attachments/assets/e288db7a-9b28-4723-a4cf-a71648b24f2e

**Comment by chengzhidada** [comment]
This is from mstsc.
https://github.com/user-attachments/assets/b143c261-9d6f-4c57-9b1d-ff89922e6f3b

**Comment by KangLin** [comment]
Please help me make sure it's the same under VNC.

**Comment by chengzhidada** [comment]
https://github.com/user-attachments/assets/b7a8c471-7bc0-4cf4-8e43-814104080e08

I tried VNC and it didn't have that.

**Comment by chengzhidada** [comment]
> Please help me make sure it's the same under VNC.


https://github.com/user-attachments/assets/3a2adffc-6d0f-4ef7-88e8-23ff9e71b789

Here is a vnc screen shot, it looks fine, I compared sdlrdp and wfreerdp and they don't have a similar problem, This problem gets worse as the resolution of the RabbitRemoteControl connection increases.

**Comment by KangLin** [comment]
Please try the version: https://github.com/KangLin/RabbitRemoteControl/releases/tag/test_develop

**Comment by chengzhidada** [comment]
> Please try the version: https://github.com/KangLin/RabbitRemoteControl/releases/tag/test_develop

I've tried and the problem persists.

**Comment by KangLin** [comment]
Please you video send my email: kl222@126.com

**Comment by chengzhidada** [comment]
I have a limited understanding of the issue regarding screen stalling in RDP remote connections. Based on certain observations, it can be noted that:    
1) As the resolution of the remote connection improves, the severity of screen stalling gradually increases. For instance, while watching a test video at a resolution of 1024x768, no delays were encountered. However, as the resolution was progressively increased, screen stalling became more prevalent and severe.   
2) The frequency of refreshes on the remote screen directly correlates with the intensity of this problem.Considering whether inefficient QT rendering or utilizing hardware-accelerated OpenCV for image rendering could potentially alleviate this issue remains uncertain. 
As an aspiring C++ developer working with QT framework, I humbly seek your guidance on where to commence troubleshooting this problem or identifying its root cause.I would greatly appreciate any advice you may offer.

**Comment by KangLin** [comment]
- Currently I have found ripples from [here](https://github.com/KangLin/RabbitRemoteControl/blob/b7664f0984e1e9a3a2cccbdb011d9b640cc8a465/Plugins/FreeRDP/Client/ConnectFreeRDP.cpp#L1445) as an image file.

- The next idea is to save the resulting image as a video file. to confirm if it's a FreeRDP write memory issue. This feature is exactly what this project needs. Are you interested in getting it done?

**Comment by chengzhidada** [comment]
Of course, I can do this kind of work, but there are still some things I don't understand.You mean to pass the existing image value to the window through the signal slot to draw the image, modify the code to save the image as a local image, and then use a third-party tool to merge the image into a video, if the video is still stuck then the problem lies in freerdp, if the picture is normal then it is the problem of drawing the window efficiency, is that right?

**Comment by chengzhidada** [comment]
> * Currently I have found ripples from [here](https://github.com/KangLin/RabbitRemoteControl/blob/b7664f0984e1e9a3a2cccbdb011d9b640cc8a465/Plugins/FreeRDP/Client/ConnectFreeRDP.cpp#L1445) as an image file.
> * The next idea is to save the resulting image as a video file. to confirm if it's a FreeRDP write memory issue. This feature is exactly what this project needs. Are you interested in getting it done?

Of course, I can do this kind of work, but there are still some things I don't understand.You mean to pass the existing image value to the window through the signal slot to draw the image, modify the code to save the image as a local image, and then use a third-party tool to merge the image into a video, if the video is still stuck then the problem lies in freerdp, if the picture is normal then it is the problem of drawing the window efficiency, is that right?

**Comment by KangLin** [comment]
Yes. Now you need a feature to save all QImage as a video file (it's in a separate thread). 
It is recommended that you write a save video class alone. 
- The input parameters are: saved Video File, Video Parameters, QImage
- The output is a video file

**Comment by KangLin** [comment]
You can refer to: https://www.cnblogs.com/feiyangqingyun/p/16954294.html
Note:  you need to use the new version of the ffmpeg interface

**Comment by chengzhidada** [comment]
Thanks, I will confirm FreeRDP write memory issue first.

**Comment by zgml** [comment]
> * Currently I have found ripples from [here](https://github.com/KangLin/RabbitRemoteControl/blob/b7664f0984e1e9a3a2cccbdb011d9b640cc8a465/Plugins/FreeRDP/Client/ConnectFreeRDP.cpp#L1445) as an image file.
> * The next idea is to save the resulting image as a video file. to confirm if it's a FreeRDP write memory issue. This feature is exactly what this project needs. Are you interested in getting it done?

Regarding this issue, I've studied the sdl code and it's a must that you need to enable the FreeRDP_SupportGraphicsPipeline feature in your project to solve the issue. Also what I mentioned in issues [21](https://github.com/KangLin/RabbitRemoteControl/issues/21) about always having ripples in the screen after building the program with freerdp3.0, no matter how much you modify the color depth, is related to this. I hope this suggestion will help you.

**Comment by chengzhidada** [comment]
After testing, I found that before QT draws the screen, the picture sent by freerdp is already ripple. 
![17288692552854](https://github.com/user-attachments/assets/08aa6d2a-6d58-4556-8754-375d6ec727a9)
![17288692948147](https://github.com/user-attachments/assets/9abd904c-4be5-446d-8e44-36b7a88aee49)

**Comment by chengzhidada** [comment]
So, this problem is due to the problem of freerdp itself.and refer to @zgml comments,it can be solve. Need to enable FreeRDP_SupportGraphicsPipeline feature.

**Comment by KangLin** [comment]
Fixed! Please test https://github.com/KangLin/RabbitRemoteControl/releases/tag/test_develop

**Comment by KangLin** [comment]
参考：
- https://learn.microsoft.com/zh-cn/openspecs/windows_protocols/ms-rdpegfx/da5c75f9-cd99-450c-98c4-014a496942b0
- https://www.cswamp.com/post/37

**Comment by chengzhidada** [comment]
> Fixed! Please test https://github.com/KangLin/RabbitRemoteControl/releases/tag/test_develop

Congratulations, my friend!But now,it have a new issue,
![企业微信截图_17288899662491](https://github.com/user-attachments/assets/8914a92b-8855-41a0-8f5d-1c0dc2df8343)
![企业微信截图_17288899777073](https://github.com/user-attachments/assets/4f2c3984-aaa2-451b-9480-ee38d06a4a81)
![企业微信截图_17288901907696](https://github.com/user-attachments/assets/9ce4c05e-d867-4a9a-aea8-830efd94e53f)

**Comment by KangLin** [comment]
You are build from source? Update RabbitCommon and RabbitRemoteControl to master laster?

**Comment by chengzhidada** [comment]
> You are build from source? Update RabbitCommon and RabbitRemoteControl to master laster?

yeah! I used your compiled release and I built from source code, and both had this issue.
