### ISSUE TITLE
Add record video to file

### ISSUE THREAD

**Issue by KangLin** [KangLin/RabbitRemoteControl#30]
Add record remote destop video to file. The record video frame is ok. please git from: https://github.com/KangLin/RabbitRemoteControl/tree/RecordVideo

CRecordVideo needs to be completed only. it is save QImage to file. 
Welcome to friends who have the ability to complete.

**Comment by KangLin** [comment]
@ chengzhidada Can you do it？

**Comment by chengzhidada** [comment]
This is a good start, I will try to implement it, it may take a long time.

**Comment by chengzhidada** [comment]
This is a good start, I will try to implement it, it may take a long time.

**Comment by KangLin** [comment]
There are three options to choose from:
- FFMPEG
- Qt6 multimedia library
- QtAv

Is it okay for a week?

**Comment by chengzhidada** [comment]
My friend, can you give me a suggestion? I don't know much about these functions. Working hours are uncertain.

**Comment by KangLin** [comment]
Suggest to  use ffmpeg . it has the simple example. modified a little to okay.

**Comment by KangLin** [comment]
Finished in 8e8cd40bfed3f7ab3aa8cd001beeb6afc0df3d95
