### ISSUE TITLE
A flash retreat associated with the clipboard

### ISSUE THREAD

**Issue by zgml** [KangLin/RabbitRemoteControl#31]
This issue appears in earlier versions as well as the latest 0.28 version。
The process of repetition：
Open Rabbit remote and a Microsoft excel program on an external computer, and then open the rdp remote desktop. If you paste  image file to the table, remote will crash. 
If  not crash, click the image in the table and press the copy combination key repeatedly. remote will almost 100% crash and no dump file will be transferred
I tried to fix this bug but without success so I reporti this issue to you, and I also found another crash bug that was 100% recurring, but I fixed it and I will submit a request to you later
![image](https://github.com/user-attachments/assets/1dda6582-ccd0-4711-872d-065ff8e05d07)

**Comment by KangLin** [comment]
See: etc/RabbitRemoteControl_logqt.ini

```
[Core]
DumpFile=true
DumpToLogFile=true
```

Please upload log and dump file.

**Comment by zgml** [comment]
[RabbitRemoteControl_33956_2024-11-28_0001.log](https://github.com/user-attachments/files/17942074/RabbitRemoteControl_33956_2024-11-28_0001.log)
I am sure that DumpFile is started, there is really no dump file generated during this process, the main program does not crash, it looks like it is disconnected, and does not pause in debug mode, which is one of the reasons I can not solve, I can not locate

**Comment by KangLin** [comment]
```
[09:39:25.579 33956|12728 W] FreeRDP.Log - Sending clipboard request with invalid flags msgFlags = 0x00000001. Correct in your client!
[09:39:25.579 33956|12728 E] FreeRDP.Log - Sending clipboard request with invalid flags msgFlags = 0x00000001. Correct in your client!
[09:39:54.050 33956|25436 W] FreeRDP.Log - Sending clipboard request with invalid flags msgFlags = 0x00000001. Correct in your client!
[09:39:54.050 33956|25436 E] FreeRDP.Log - Sending clipboard request with invalid flags msgFlags = 0x00000001. Correct in your client!
[09:40:43.321 33956|25436 W] FreeRDP.Log - Sending clipboard request with invalid flags msgFlags = 0x00000001. Correct in your client!
[09:40:43.321 33956|25436 E] FreeRDP.Log - Sending clipboard request with invalid flags msgFlags = 0x00000001. Correct in your client!
[09:40:43.324 33956|12728 E] FreeRDP.Log - ServerFormatListResponse failed with error 2147500037!
```
This is error.

more information:

```
[Rules]
;*=false
*.debug=false
;*.warning=false
```

comment:

```
;*.debug=false
```

**Comment by zgml** [comment]
[RabbitRemoteControl_26532_2024-11-28_0001.log](https://github.com/user-attachments/files/17942330/RabbitRemoteControl_26532_2024-11-28_0001.log)

**Comment by zgml** [comment]
New repetition process: Without any additional software, just randomly select a file outside the rabbit, such as txt, and then continuously press the copy combination key, the client will blink back

**Comment by KangLin** [comment]
Take time to refactor the clipboard, and copy files from the server to the client

在 2024-11-29 16:30:56，zgml ***@***.***> 写道：


New repetition process: Without any additional software, just randomly select a file outside the rabbit, such as txt, and then continuously press the copy combination key, the client will blink back

**Comment by zgml** [comment]
For the above problems, multiple copy file crash can be solved by adding locks, as for the copy excel within the picture crash problem, my understanding is that the picture in the system and the software within the picture is different, need additional processing, can be so understood? This problem is serious enough to require code refactoring?

**Comment by KangLin** [comment]
copy file to client form service that is need refactor.

**Comment by zgml** [comment]
Client to controlled end: Copy a text, then copy a different text, must be a different text, the interface will crush, 100% probability

**Comment by zgml** [comment]
> copy file to client form service that is need refactor.

But the current problems are all in the client to service, I want to fix it, Repeated replication result to crash problem, I added the lock, the current state seems OK

> Client to controlled end: Copy a text, then copy a different text, must be a different text, the interface will crush, 100% probability

There should be a cleaning action before the next copy?

**Comment by KangLin** [comment]
I has not word, but I am use wps and libreoffice to success copy image to server from client.

**Comment by KangLin** [comment]
Because the entire clipboard operation is on the same background thread, it is synchronized.

**Comment by zgml** [comment]
> I has not word, but I am use wps and libreoffice to success copy image to server from client.



> I has not word, but I am use wps and libreoffice to success copy image to server from client.

No picture needed, you write demo1 demo2 on wps, then open the rabbit link, copy demo1, then copy demo2 again, and the rabbit crashes

**Comment by zgml** [comment]
> I has not word, but I am use wps and libreoffice to success copy image to server from client.


https://github.com/user-attachments/assets/7a4e8946-4ea1-4bbd-9fcf-44f61ed088ef

**Comment by KangLin** [comment]
I am success. please upload log file.

**Comment by KangLin** [comment]
Please enable debug. then upload log

**Comment by KangLin** [comment]
https://github.com/user-attachments/assets/b39989b2-7c5e-4bc4-9802-d6b69f1d6b5a

**Comment by KangLin** [comment]
You can try to see if freerdp v3.8.0 has this issue.

**Comment by zgml** [comment]
> You can try to see if freerdp v3.8.0 has this issue in your environment.

😢😢😢As you might expect, wfreerdp has the exact same bug

**Comment by KangLin** [comment]
I am use freerdp v2.10 in ubuntu. You can try to see if freerdp v2.9 to 2.10 has this issue in your environment.

**Comment by zgml** [comment]
> I am use freerdp v2.10 in ubuntu. You can try to see if freerdp v2.9 to 2.10 has this issue in your environment.

Low versions of wfreerdp are not easy to find, I can only get the latest few versions in their workflow artifacts, my purpose is to find the problem，I feel the problem has something to do with it，[freerdp iussue 10472](https://github.com/FreeRDP/FreeRDP/pull/10472) What I wonder is, according to the time node, this problem should have been fixed, why is there still a problem in testing their latest version?

**Comment by KangLin** [comment]
> Low versions of wfreerdp are not easy to find, I can only get the latest few versions in their workflow artifacts, my purpose is to find the problem，I feel the problem has something to do with it，[freerdp iussue 10472](https://github.com/FreeRDP/FreeRDP/pull/10472) What I wonder is, according to the time node, this problem should have been fixed, why is there still a problem in testing their latest version?

- Judging by the logs, these are two different issues.
- I think you should git pull, then recompile, and then test.
- Please upload log file(enable debug) above issues.

**Comment by zgml** [comment]
> > Low versions of wfreerdp are not easy to find, I can only get the latest few versions in their workflow artifacts, my purpose is to find the problem，I feel the problem has something to do with it，[freerdp iussue 10472](https://github.com/FreeRDP/FreeRDP/pull/10472) What I wonder is, according to the time node, this problem should have been fixed, why is there still a problem in testing their latest version?
> 
> * Judging by the logs, these are two different issues.
> * I think you should git pull, then recompile, and then test.
> * Please upload log file(enable debug) above issues.

I will try, but to my confusion, I have found three Windows 10 and one virtual Windows 10, they all have this problem, but your device does not

**Comment by KangLin** [comment]
So than I am need your new log file(enable debug). The log be can look issues.

**Comment by zgml** [comment]
> So than I am need your new log file(enable debug). The log be can look issues. Also I use ubuntu, freerdp v2. 　So I'm wondering if freerdpv2 will be issues in your environment as well

The crash log file is pretty much the same as what I uploaded earlier, and I used debug mode to debug wfreerdp with the same error code.

Below is a partial log from wfreerdp

17:25:24:118] [51168:0000bca4] [INFO][com.freerdp.client.windows] - [wf_end_paint]: Window is shown!
[17:25:29:580] [51168:0000bca4] [INFO][com.freerdp.channels.rdpsnd.client] - [rdpsnd_load_device_plugin]: [dynamic] Loaded fake backend for rdpsnd
[17:25:39:957] [51168:000076cc] [ERROR][com.freerdp.channels.cliprdr.client] - [cliprdr_process_format_list_response]: ServerFormatListResponse failed with error 2147500037!
[17:25:39:958] [51168:000076cc] [ERROR][com.freerdp.channels.cliprdr.client] - [cliprdr_order_recv]: cliprdr_process_format_list_response failed with error 2147500037!
[17:25:39:958] [51168:000076cc] [ERROR][com.freerdp.channels.addin] - [channel_client_thread_proc]: msg_handler failed with error 2147500037!
线程 0x76cc 已退出，返回值为 2147500037 (0x80004005)。
[17:25:39:961] [51168:00006484] [ERROR][com.freerdp.core] - [checkChannelErrorEvent]: cliprdr_virtual_channel_client_thread reported an error. Error was 2147500037
[17:25:39:961] [51168:00006484] [ERROR][com.freerdp.core] - [freerdp_check_event_handles]: checkChannelErrorEvent() failed - 0
[17:25:39:962] [51168:00006484] [INFO][com.freerdp.client.common] - [client_auto_reconnect_ex]: Network disconnect!
[17:25:39:962] [51168:00006484] [ERROR][com.freerdp.client.windows] - [wf_client_thread]: Failed to check FreeRDP file descriptor

And that's actually what caused the previous copy image crash

[RabbitRemoteControl_6020_2024-12-04_0001.log](https://github.com/user-attachments/files/18004275/RabbitRemoteControl_6020_2024-12-04_0001.log)

**Comment by KangLin** [comment]
Because the server does not support the clipboard data format, so the error is returned. Fix: 5c77217e

**Comment by KangLin** [comment]
@zgml please test: https://github.com/KangLin/RabbitRemoteControl/actions/runs/12173289050/artifacts/2277340334

**Comment by zgml** [comment]
> @zgml please test: https://github.com/KangLin/RabbitRemoteControl/actions/runs/12173289050/artifacts/2277340334

I tested it and it no longer crashed, but the replication was no longer sensitive, and in many cases it had to be replicated twice

**Comment by KangLin** [comment]
try: https://github.com/KangLin/RabbitRemoteControl/actions/runs/12173289050/artifacts/2277340334
and upload log file(enable debug)

**Comment by zgml** [comment]
[RabbitRemoteControl_24972_2024-12-05_0001.log](https://github.com/user-attachments/files/18018543/RabbitRemoteControl_24972_2024-12-05_0001.log)

Just copy ordinary text, the first time normal, subsequent copy almost always have to press twice copy
