### ISSUE TITLE
玉兔rdp效果比mstsc效果差多了。请问有什么方式可以调整吗

### ISSUE THREAD

**Issue by law15390643835** [KangLin/RabbitRemoteControl#36]
![f0390423b00f560ff4009009f153afa](https://github.com/user-attachments/assets/18f1ff14-9ff3-4ba0-8843-a4ea374d1643)

主要问题是：字体虚，请问要怎么调整，才能达到mstsc的效果呢

**Comment by KangLin** [comment]
- 选择保持高宽比缩放。或者使用原始尺寸。
- 设置屏幕参数与你本地屏幕相同

**Comment by law15390643835** [comment]
> * 选择保持高宽比缩放。或者使用原始尺寸。
> * 设置屏幕参数与你本地屏幕相同

怎么设置呢？

**Comment by KangLin** [comment]
![图片](https://github.com/user-attachments/assets/d6e666f3-ebfc-43cf-af9e-030a590f1796)

https://github.com/user-attachments/assets/18e7372a-7bd4-46d8-848a-6c8d7afb8af1

**Comment by law15390643835** [comment]
玉兔RDP支持全屏吗？

**Comment by KangLin** [comment]
支持

**Comment by law15390643835** [comment]
> 支持

没找到设置的地方，请问在哪里设置呢

**Comment by KangLin** [comment]
菜单栏和工具栏上都有
